
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ivan
  password: 1234
  host: localhost
  port: 5432


development:
  <<: *default
  database: lessons_shedule_development

test:
  <<: *default
  database: lessons_shedule_test
